package es.uma.informatica.sii.buzzerbeaters.test;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BuzzerBeatersIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void inicioAdmin() {
    driver.get("http://localhost:8080/BuzzerBeaters-war/");
    driver.manage().window().setSize(new Dimension(876, 1075));
    driver.findElement(By.linkText("Login para administradores")).click();
    driver.findElement(By.id("adminLogin:user")).click();
    driver.findElement(By.id("adminLogin:user")).sendKeys("Fulanito");
    driver.findElement(By.id("adminLogin:pass")).sendKeys("pass");
    driver.findElement(By.id("adminLogin:botonLogin")).click();
    driver.findElement(By.cssSelector("h3")).click();
    assertThat(driver.findElement(By.id("mensBienv")).getText(), is("Bienvenido Fulanito"));
  }
  @Test
  public void loginnormal() {
    driver.get("http://localhost:8080/BuzzerBeaters-war/");
    driver.manage().window().setSize(new Dimension(876, 1040));
    driver.findElement(By.id("login:user")).click();
    driver.findElement(By.id("login:user")).sendKeys("Menganito");
    driver.findElement(By.id("login:pass")).sendKeys("pass");
    driver.findElement(By.id("login:botonLogin")).click();
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.findElement(By.id("mensBienv")).getText(), is("Bienvenido a la Página principal de clientes"));
  }
  @Test
  public void altaClienteIndividual() {
    driver.get("http://localhost:8080/BuzzerBeaters-war/");
    driver.manage().window().setSize(new Dimension(876, 1040));
    driver.findElement(By.linkText("Login para administradores")).click();
    driver.findElement(By.id("adminLogin:user")).click();
    driver.findElement(By.id("adminLogin:user")).sendKeys("Fulanito");
    driver.findElement(By.id("adminLogin:pass")).sendKeys("pass");
    driver.findElement(By.id("adminLogin:botonLogin")).click();
    driver.findElement(By.id("botonAltaIndividual")).click();
    driver.findElement(By.id("altaCIndividual:username")).click();
    driver.findElement(By.id("altaCIndividual:username")).sendKeys("uno");
    driver.findElement(By.id("altaCIndividual:pass")).sendKeys("pass");
    driver.findElement(By.id("altaCIndividual:nombre")).sendKeys("unomismo");
    driver.findElement(By.id("altaCIndividual:apellido")).sendKeys("apellido");
    driver.findElement(By.id("altaCIndividual:fechaNacimiento")).sendKeys("1800-02-03");
    driver.findElement(By.id("altaCIndividual:identificacion")).sendKeys("11111p");
    driver.findElement(By.id("altaCIndividual:direccion")).sendKeys("calle pito");
    driver.findElement(By.id("altaCIndividual:ciudad")).sendKeys("Malaga");
    driver.findElement(By.id("altaCIndividual:pais")).sendKeys("España");
    driver.findElement(By.id("altaCIndividual:cp")).sendKeys("29000");
    driver.findElement(By.id("altaCIndividual:botonAltaCIndiv")).click();
    driver.findElement(By.id("altaCIndividual")).click();
    assertThat(driver.findElement(By.id("altaCIndividual:boton")).getText(), is("El cliente se ha dado de alta correctamente"));
  }
  @Test
  public void altaEmpresa() {
    driver.get("http://localhost:8080/BuzzerBeaters-war/");
    driver.manage().window().setSize(new Dimension(876, 1040));
    driver.findElement(By.linkText("Login para administradores")).click();
    driver.findElement(By.id("adminLogin:user")).click();
    driver.findElement(By.id("adminLogin:user")).sendKeys("Fulanito");
    driver.findElement(By.id("adminLogin:pass")).sendKeys("pass");
    driver.findElement(By.id("adminLogin:botonLogin")).click();
    driver.findElement(By.id("botonAltaEmpresa")).click();
    driver.findElement(By.id("altaCEmpresa:razonSocial")).click();
    driver.findElement(By.id("altaCEmpresa:razonSocial")).sendKeys("empre");
    driver.findElement(By.id("altaCEmpresa:identificacion")).click();
    driver.findElement(By.id("altaCEmpresa:identificacion")).sendKeys("b290909090");
    driver.findElement(By.id("altaCEmpresa:direccion")).click();
    driver.findElement(By.id("altaCEmpresa:direccion")).sendKeys("calle industria");
    driver.findElement(By.id("altaCEmpresa:ciudad")).sendKeys("Malaga");
    driver.findElement(By.id("altaCEmpresa:pais")).sendKeys("España");
    driver.findElement(By.id("altaCEmpresa:cp")).sendKeys("29018");
    driver.findElement(By.id("altaCEmpresa:botonAltaCEmpresa")).click();
    driver.findElement(By.id("altaCEmpresa")).click();
    assertThat(driver.findElement(By.id("altaCEmpresa:botonEmpresa")).getText(), is("Empresa creada correctamente"));
  }
}
